apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "webapp-chart.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.backend.secret.SECRET_KEY | b64enc | quote }}
